---
title: "saeesh_resume"
author: "Saeesh Mangwani"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['resume.css']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---
<!--- start of code for importing the font awesome set of styles--->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" integrity="sha256-46qynGAkLSFpVbEBog43gvNhfrOj+BmwXdxFgVK/Kvc=" crossorigin="anonymous" />
<!--- end of code for font awesome--->

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

# Loading libraries
library(tidyverse)
library(glue)
library(rmarkdown)

# Setting variables to help with loading data

# url for the google sheets 
positions_sheet_loc <- "https://docs.google.com/spreadsheets/d/1Z3Eu2Tjx7zgI9mTzMUi_EhieOOELmJKj7CXjGc9Iyfg/edit?usp=sharing"

# Is this sheet available for anyone to read? If you're using a private sheet
# set this to false and go to gather_data.R and run the data loading manually
# once to cache authentication
sheet_is_publicly_readable <- TRUE

# Is the goal of this knit to build a document that is exported to PDF? If so
# set this to true to have links turned into footnotes at the end of the
# document
PDF_EXPORT <- FALSE


# A global (gasp) variable that holds all the links that were inserted for
# placement at the end
links <- c()

# ======================================================================
# Now we source two external scripts. One contains functions for building the
# text output and the other loads up our data from either googlesheets or csvs

# Functions for building sections from CSV data
source('parsing_functions.R') 

# Load data for CV/Resume
source('gather_data.R')

# Now we just need to filter down the position data to include less verbose
# categories and only the entries we have designated for the resume
position_data <- position_data %>% 
  filter(in_resume)
```

<!-- Creating the aside section of the CV  -->
Aside
================================================================================

<!-- Using contact data pulled from the google docs to glue an html list that adds contact info -->
## CONTACT

```{r}
contact_info %>% 
  glue_data("- <i class='fa fa-{icon}'></i> {contact}", .sep="\n")
```

<!-- Adding skills the same way -->
## SKILLS
```{r}
skills %>% 
  glue_data("- <i class='{icon}'></i> {skill} \n\n")
```

<!-- # Adding languages manually -->
## LANGUAGES

**English:** Native

**Hindi:** Native

**Spanish:** Beginner

<br>

<!-- # Adding an acknowledgement section (kept the disclaimer tag so as to not have to over-edit the css) -->
Acknowledgement {#disclaimer}
--------------------------------------------------------------------------------

This resume was developed using the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.

<!-- The main body of the cv -->
Main
================================================================================

<!-- # Name and description -->
Saeesh Mangwani {#title}
--------------------------------------------------------------------------------

```{r}
print_text_block(text_blocks, 'intro')
```

<!-- Education information -->
Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('education')
```

<!-- Selected ork experience information (Selection done using a TRUE-FALSE column in the google doc) -->
Selected Work Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('work_experience')
```

<!-- GIS Experience (Can be removed or added through commmenting out as per need) -->
GIS Experience {data-icon=globe}
--------------------------------------------------------------------------------
```{r}
position_data %>% print_section('gis_experience')
```

<!-- Lab and/or field research experience (Can be removed or added through commmenting out as per need) -->
<!-- Lab Experience {data-icon=flask} -->
<!-- -------------------------------------------------------------------------------- -->
<!-- ```{r} -->
<!-- position_data %>% print_section('lab_experience') -->
<!-- ``` -->

<!-- Selected personal project information (selection done using a TRUE-FALSE column in the google doc) -->
Selected Personal Projects {data-icon=share-alt}
--------------------------------------------------------------------------------
```{r}
position_data %>% print_section('personal_initiatives')
```

